#!/usr/bin/env zsh
# Description:
#   Self management of zplug

if ! __zplug::base::base::zpluged "NemesisRE/zplug"; then
    __zplug::io::print::f \
        --die \
        --zplug \
        "NemesisRE/zplug: not managed yet\n"
    return 1
fi

ln -snf \
    "$ZPLUG_REPOS/NemesisRE/zplug/init.zsh" \
    "$ZPLUG_HOME/init.zsh"
